# Generated by Django 4.1.1 on 2022-10-16 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 16, 8, 31, 158355)),
        ),
    ]
