# Generated by Django 4.1.1 on 2022-10-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_projects_createat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='createAt',
        ),
        migrations.AlterField(
            model_name='projects',
            name='donateCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='isFeatured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total',
            field=models.IntegerField(),
        ),
    ]
