# Generated by Django 4.1.1 on 2022-10-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contributionID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=20)),
                ('projectID', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
